### PR TITLE
classes/types with import

### PR DESCRIPTION
**Pull request by Schokokex**
**imports are generated**

added classes and types generator.
Handlebars are in seperated files for readability and cleaniness.

**ts.js** file can be configured with "**type**", "**interface**" or "**class**"

might add an import too much, e.g. _MessageEntity_ and _Message_ if only _MessageEntity_ is needed

### CODE REVIEW

**Comment by devmattrick** [comment]
Does this replace #10?

**Comment by Schokokex** [comment]
yes, i proposed both so you could choose

this one is more advanced, because it has the import statements

**Comment by devmattrick** [comment]
Gotcha! Thanks again for the contributions!

One last request is to not commit data.json as this should be generated at runtime and is not necessary to include in this repo. Really should be .gitignore-d but I forgot to include it 😬 If you just delete it off of your branch I can squash and merge so its not in commit history. Thanks again!

**Comment by Schokokex** [comment]
kay :)

**Comment by devmattrick** [comment]
Thanks for the help!

**Pull request merged**
